; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "RoadX Monitoring System"
#define MyAppVersion "2.12"
#define MyAppPublisher "Boris Istigechev"
#define MyAppURL "https://github.com/neoclassic-alt"
#define MyAppExeName "program.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C56FB75B-D75B-4493-913C-C79705748A41}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=cvsetup
SetupIconFile=D:\Борис\Учебные файлы\Дипломная работа\program+\assets\images\app.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Components: required

[Components]
Name: "required"; Description: "Необходимые файлы"; Types: full custom compact; Flags: fixed
Name: "plugins"; Description: "Плагины"; Types: full;
Name: "plugins\detectors"; Description: "Распознавание"; Types: full;
Name: "plugins\detectors\car_detector"; Description: "Распознавание машин"; Types: full
Name: "plugins\detectors\person_detector"; Description: "Распознавание людей"; Types: full
Name: "plugins\detectors\traffic_light_detector"; Description: "Распознавание светофоров"; Types: full
Name: "plugins\detectors\stop_detector"; Description: "Распознавание знаков «STOP»"; Types: full
Name: "plugins\detectors\traffic_light_color"; Description: "Распознавание цвета светофора"; Types: full;
Name: "plugins\contours"; Description: "Контуры"; Types: full;
Name: "plugins\violations"; Description: "Обнаружение нарушений правил"; Types: full;
Name: "plugins\violations\wrong_crossing"; Description: "Нарушение правил пешеходного перехода"; Types: full;
Name: "plugins\violations\running_red_light"; Description: "Проезд на красный свет"; Types: full;
Name: "plugins\old_plugins"; Description: "Старые плагины"; Types: full;
Name: "configurations"; Description: "Файлы конфигураций цепочек плагинов"; Types: full;

[Types]
Name: "full"; Description: "Полная"
Name: "compact"; Description: "Минимальная"
Name: "custom"; Description: "Выборочная"; Flags: iscustom

[Files]
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion; Components: "required"
Source: "C:\ProgramData\cv_experiments\settings.json"; DestDir: "C:\ProgramData\cv_experiments"; Flags: ignoreversion; Components: "required"
Source: "C:\ProgramData\cv_experiments\journal.txt"; DestDir: "C:\ProgramData\cv_experiments"; Flags: ignoreversion; Components: "required"
Source: "C:\ProgramData\cv_experiments\letter.txt"; DestDir: "C:\ProgramData\cv_experiments"; Flags: ignoreversion; Components: "required"
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\plugin_system\plugins\car_detector\*"; DestDir: "{app}\plugins\car_detector"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\detectors\car_detector" 
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\plugin_system\plugins\person_detector\*"; DestDir: "{app}\plugins\person_detector"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\detectors\person_detector"
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\plugin_system\plugins\traffic_light_detector\*"; DestDir: "{app}\plugins\traffic_light_detector"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\detectors\traffic_light_detector"
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\plugin_system\plugins\stop_detector\*"; DestDir: "{app}\plugins\stop_detector"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\detectors\stop_detector"
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\plugin_system\plugins\traffic_light_color\*"; DestDir: "{app}\plugins\traffic_light_color"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\detectors\traffic_light_color"
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\plugin_system\plugins\set_points_pedestrian_crossing\*"; DestDir: "{app}\plugins\set_points_pedestrian_crossing"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\contours"
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\plugin_system\plugins\set_points_road\*"; DestDir: "{app}\plugins\set_points_road"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\contours"
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\plugin_system\plugins\running_red_light\*"; DestDir: "{app}\plugins\running_red_light"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\violations\running_red_light"
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\plugin_system\plugins\wrong_crossing\*"; DestDir: "{app}\plugins\wrong_crossing"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\violations\wrong_crossing"
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\assets\*"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "required"
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\plugin_system\common\*"; DestDir: "{app}\common"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "required"
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\plugin_system\presets\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "configurations"
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\plugin_system\old_plugins\*"; DestDir: "{app}\old_plugins"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\old_plugins"
Source: "D:\Борис\Учебные файлы\Дипломная работа\program+\plugin_system\old_plugins\*"; DestDir: "{app}\old_plugins"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "required"
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\assets\images\app.ico"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent runascurrentuser

