; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Computer Vision Experiments"
#define MyAppVersion "0.8"
#define MyAppPublisher "Boris Istigechev"
#define MyAppURL "https://github.com/neoclassic-alt"
#define MyAppExeName "program.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A327BE9F-75BC-4CEB-8BE7-E6CC440FB5E1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=cvsetup
SetupIconFile=E:\opencv\cv_program_build\assets\images\icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Components: required
Name: "desktopicon_keygen"; Description: "{cm:CreateDesktopIcon} (кейген)"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; Components: keygen

[Components]
Name: "required"; Description: "Необходимые файлы"; Types: full custom compact; Flags: fixed
Name: "keygen"; Description: "Кейген"; Types: full;
Name: "plugins"; Description: "Плагины"; Types: full;
Name: "plugins\detectors"; Description: "Распознавание"; Types: full;
Name: "plugins\detectors\car_detector"; Description: "Распознавание машин"; Types: full
Name: "plugins\detectors\person_detector"; Description: "Распознавание людей"; Types: full
Name: "plugins\detectors\traffic_light_detector"; Description: "Распознавание светофоров"; Types: full
Name: "plugins\detectors\stop_detector"; Description: "Распознавание знаков «STOP»"; Types: full
Name: "plugins\detectors\traffic_light_color"; Description: "Распознавание цвета светофора"; Types: full;
Name: "plugins\contours"; Description: "Контуры"; Types: full;
Name: "plugins\violations"; Description: "Обнаружение нарушений правил"; Types: full;
Name: "plugins\violations\wrong_crossing"; Description: "Нарушение правил пешеходного перехода"; Types: full;
Name: "plugins\violations\running_red_light"; Description: "Проезд на красный свет"; Types: full;
Name: "plugins\old_plugins"; Description: "Старые плагины"; Types: full;
Name: "configurations"; Description: "Файлы конфигураций цепочек плагинов"; Types: full;

[Types]
Name: "full"; Description: "Полная"
Name: "compact"; Description: "Минимальная"
Name: "custom"; Description: "Выборочная"; Flags: iscustom

[Files]
Source: "E:\opencv\cv_program_build\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion; Components: "required"
Source: "E:\opencv\cv_program_build\program.cmd"; DestDir: "{app}"; Flags: ignoreversion; Components: "required"
Source: "E:\opencv\cv_program_files\settings.json"; DestDir: "C:\ProgramData\cv_experiments"; Flags: ignoreversion; Components: "required"
Source: "E:\opencv\cv_program_files\journal.txt"; DestDir: "C:\ProgramData\cv_experiments"; Flags: ignoreversion; Components: "required"
Source: "E:\opencv\cv_program_files\letter.txt"; DestDir: "C:\ProgramData\cv_experiments"; Flags: ignoreversion; Components: "required"
Source: "E:\opencv\cv_program_build\plugins\car_detector\*"; DestDir: "{app}\plugins\car_detector"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\detectors\car_detector" 
Source: "E:\opencv\cv_program_build\plugins\person_detector\*"; DestDir: "{app}\plugins\person_detector"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\detectors\person_detector"
Source: "E:\opencv\cv_program_build\plugins\traffic_light_detector\*"; DestDir: "{app}\plugins\traffic_light_detector"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\detectors\traffic_light_detector"
Source: "E:\opencv\cv_program_build\plugins\stop_detector\*"; DestDir: "{app}\plugins\stop_detector"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\detectors\stop_detector"
Source: "E:\opencv\cv_program_build\plugins\traffic_light_color\*"; DestDir: "{app}\plugins\traffic_light_color"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\detectors\traffic_light_color"
Source: "E:\opencv\cv_program_build\plugins\set_points_pedestrian_crossing\*"; DestDir: "{app}\plugins\set_points_pedestrian_crossing"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\contours"
Source: "E:\opencv\cv_program_build\plugins\set_points_road\*"; DestDir: "{app}\plugins\set_points_road"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\contours"
Source: "E:\opencv\cv_program_build\plugins\running_red_light\*"; DestDir: "{app}\plugins\running_red_light"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\violations\running_red_light"
Source: "E:\opencv\cv_program_build\plugins\wrong_crossing\*"; DestDir: "{app}\plugins\wrong_crossing"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\violations\wrong_crossing"
Source: "E:\opencv\cv_program_build\assets\*"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "required"
Source: "E:\opencv\cv_program_build\common\*"; DestDir: "{app}\common"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "required"
Source: "E:\opencv\cv_program_build\keygen\*"; DestDir: "{app}\keygen"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "keygen"
Source: "E:\opencv\cv_program_files\running_red_light.json"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "configurations"
Source: "E:\opencv\cv_program_files\wrong_crossing_detection.json"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "configurations"
Source: "E:\opencv\cv_program_build\old_plugins\*"; DestDir: "{app}\old_plugins"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: "plugins\old_plugins"
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\assets\images\icon.ico"
Name: "{autodesktop}\Keygen"; Filename: "{app}\keygen\create_key.exe"; Tasks: desktopicon_keygen; IconFilename: "{app}\keygen\keys.ico"; Components: keygen

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent runascurrentuser

