from components.functions import AppInfo as app_info
import dearpygui.dearpygui as dpg
from components.storage import storage

def get_assets():
    with dpg.texture_registry(tag="texture_registry"):
        dpg.add_raw_texture(2000, 2000, storage.current_data, format=dpg.mvFormat_Float_rgba, tag="main_image")
        app_info.add_static_texture(r"assets/images/crosshair-three.png", "crosshair_img")
        app_info.add_static_texture(r"assets/images/app-icon-128x128.png", "app_splash")
        app_info.add_static_texture(r"assets/images/app-icon-32x32.png", "app_logo")
        app_info.add_static_texture(r"assets/new-icons/help.png", "help_img")
        app_info.add_static_texture(r"assets/new-icons/red-point.png", "red_point")
        app_info.add_static_texture(r"assets/new-icons/add-image.png", "add_image")
        app_info.add_static_texture(r"assets/new-icons/add-folder.png", "add_folder")
        app_info.add_static_texture(r"assets/new-icons/globus-add.png", "add_from_internet")
        app_info.add_static_texture(r"assets/new-icons/globus-add-inactive.png", "add_from_internet_inactive")
        app_info.add_static_texture(r"assets/new-icons/add-video.png", "add_video")
        app_info.add_static_texture(r"assets/new-icons/add-video-inactive.png", "add_video_inactive")
        app_info.add_static_texture(r"assets/new-icons/next-file.png", "next_file")
        app_info.add_static_texture(r"assets/new-icons/prev-file.png", "prev_file")
        app_info.add_static_texture(r"assets/new-icons/more-files.png", "more_files")
        app_info.add_static_texture(r"assets/new-icons/image-close.png", "close_image")
        app_info.add_static_texture(r"assets/new-icons/image-close-inactive.png", "close_image_inactive")
        app_info.add_static_texture(r"assets/new-icons/delete-temp-files.png", "delete_temp_files")
        app_info.add_static_texture(r"assets/new-icons/zoom-minus-inactive.png", "zoom_minus_inactive")
        app_info.add_static_texture(r"assets/new-icons/zoom-plus-inactive.png", "zoom_plus_inactive")
        app_info.add_static_texture(r"assets/new-icons/zoom-minus-o.png", "zoom_minus")
        app_info.add_static_texture(r"assets/new-icons/zoom-plus-o.png", "zoom_plus")
        app_info.add_static_texture(r"assets/new-icons/expand.png", "expand")
        app_info.add_static_texture(r"assets/new-icons/demo-badge.png", "demo_badge")
        app_info.add_static_texture(r"assets/new-icons/next-file-inactive.png", "next_file_inactive")
        app_info.add_static_texture(r"assets/new-icons/prev-file-inactive.png", "prev_file_inactive")
        app_info.add_static_texture(r"assets/new-icons/more-files-inactive.png", "more_files_inactive")
        app_info.add_static_texture(r"assets/new-icons/play.png", "play")
        app_info.add_static_texture(r"assets/new-icons/pause.png", "pause")
        app_info.add_static_texture(r"assets/new-icons/previous-frame.png", "prev_frame")
        app_info.add_static_texture(r"assets/new-icons/next-frame.png", "next_frame")
        app_info.add_static_texture(r"assets/new-icons/skip-backward.png", "skip_backward")
        app_info.add_static_texture(r"assets/new-icons/skip-forward.png", "skip_forward")
        app_info.add_static_texture(r"assets/new-icons/lock.png", "locked")
        app_info.add_static_texture(r"assets/new-icons/search-icon.png", "search_icon")
        app_info.add_static_texture(r"assets/new-icons/image.png", "image")
        app_info.add_static_texture(r"assets/new-icons/image-irrelevant.png", "image_irrelevant")
        app_info.add_static_texture(r"assets/new-icons/image-actual.png", "image_actual")
        app_info.add_static_texture(r"assets/new-icons/video.png", "video")
        app_info.add_static_texture(r"assets/new-icons/video-irrelevant.png", "video_irrelevant")
        app_info.add_static_texture(r"assets/new-icons/video-actual.png", "video_actual")
        app_info.add_static_texture(r"assets/new-icons/download.png", "download")
        app_info.add_static_texture(r"assets/new-icons/download-irrelevant.png", "download_irrelevant")
        app_info.add_static_texture(r"assets/new-icons/download-actual.png", "download_actual")
        app_info.add_static_texture(r"assets/new-icons/ip-camera.png", "ip_camera")
        app_info.add_static_texture(r"assets/new-icons/current-file.png", "current_file")
        app_info.add_static_texture(r"assets/new-icons/close-small.png", "close_small")
        app_info.add_static_texture(r"assets/new-icons/circle-close.png", "circle_close")